require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe OrdersController do
  render_views

  before(:each) do
    @user = test_sign_in(Factory(:user, :admin => true))
  end

  def mock_order(stubs={})
    @mock_order ||= mock_model(Order, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all orders as @orders" do
      #Order.stub(:all) { [mock_order] }
      mock_order = Factory(:order)
      visit '/orders'
      #save_and_open_page
      #assigns(:orders).should eq([mock_order])
      page.should have_content("1 Found")
    end
  end

end
